name: Makefile CI

on:
  push:
    branches: [ "j2coreltecis-user-8.1.0-M1AJB-J260FXXSAAVK2-release-keys" ]
  pull_request:
    branches: [ "j2coreltecis-user-8.1.0-M1AJB-J260FXXSAAVK2-release-keys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
